#!/usr/bin/env bash
# A script that installs nginx server ubuntu linux distro.
# The installed server listens to port 80 HTTP connection
# And serves a default page index.html on the HTTP.

sudo apt-get update -y

sudo apt-get install nginx -y

echo 'Hello World!' > /var/www/html/index.html

service nginx restart
